name: TV Market Bot

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Install Chromium
        run: |
          playwright install chromium

      - name: Run Test
        run: |
          python test.py
          
      - name: List Files
        run: ls -lah

      - name: Find Files
        run: find . -name "*.html" -o -name "*.png"
      - name: Upload HTML
        uses: actions/upload-artifact@v4
        with:
          name: tradingview-html
          path: page.html

      - name: Upload Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: tradingview-screenshot
          path: page.png
